name: Deploy to EC2

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy over SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          mkdir /home/ubuntu/my-app
          cd /home/ubuntu/my-app
          git clone https://github.com/emirhanmurat/my-app.git .
          docker build -t my-app .
          docker stop my-app || true && docker rm my-app || true
          docker run -d -p 8000:8000 --name my-app my-app
